// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package pkg

// Injectors from wire.go:

func InitializeUserService() *UserService {
	mySQLUserRepository := NewMySQLUserRepository()
	userService := NewUserService(mySQLUserRepository)
	return userService
}
